package main

import (
	"strings"
	"text/template"

	"github.com/spf13/cobra"
)

// the three registries generate the same file: named constants of one Go type.
// They differ only in which JSON field carries the value, which is what this
// interface hides so a single template can serve all of them.
type constant interface {
	Ident() string
	Value() int
}

type stateConstant struct {
	Name  string `json:"name"`
	State int    `json:"defaultState"`
}

func (c stateConstant) Ident() string {
	return ident(c.Name)
}

func (c stateConstant) Value() int {
	return c.State
}

type idConstant struct {
	Name string `json:"name"`
	ID   int    `json:"id"`
}

func (c idConstant) Ident() string {
	return ident(c.Name)
}

func (c idConstant) Value() int {
	return c.ID
}

var constantSource = template.Must(template.New("constants").Parse(
	`// Code generated by gen {{.Name}} {{.Version}}; DO NOT EDIT.

package {{.Package}}

import gocraft "github.com/lrnxzz/go-craft"

const (
{{- range .Values}}
	{{.Ident}} {{$.Kind}} = {{.Value}}
{{- end}}
)
`))

// a registry is named after the package it generates into, and its asset and
// output files follow that same name
func constants[T constant](name, kind string) generator[[]T] {
	return generator[[]T]{
		name:     name,
		pkg:      name,
		kind:     kind,
		asset:    name + ".json",
		output:   name + ".go",
		template: constantSource,
	}
}

func blocksCommand() *cobra.Command {
	blocks := constants[stateConstant]("blocks", "gocraft.BlockState")

	return blocks.command()
}

func biomesCommand() *cobra.Command {
	biomes := constants[idConstant]("biomes", "gocraft.BiomeID")

	return biomes.command()
}

func itemsCommand() *cobra.Command {
	items := constants[idConstant]("items", "gocraft.ItemID")

	return items.command()
}

func ident(name string) string {
	var b strings.Builder
	for _, part := range strings.Split(name, "_") {
		if part != "" {
			b.WriteString(strings.ToUpper(part[:1]) + part[1:])
		}
	}

	return b.String()
}
