package main

import (
	"text/template"

	"github.com/spf13/cobra"
)

type materialSpeeds map[string]map[int]float64

var materialSource = template.Must(template.New("materials").Parse(
	`// Code generated by gen {{.Name}} {{.Version}}; DO NOT EDIT.

package {{.Package}}

var materials = map[string]toolSpeeds{
{{- range $material, $tools := .Values}}
	"{{$material}}": {
{{- range $item, $speed := $tools}}
		{{$item}}: {{$speed}},
{{- end}}
	},
{{- end}}
}
`))

func materialsCommand() *cobra.Command {
	materials := generator[materialSpeeds]{
		name:     "materials",
		pkg:      "blocks",
		asset:    "materials.json",
		output:   "materials.go",
		template: materialSource,
	}

	return materials.command()
}
