// Code generated by gen biomes 765; DO NOT EDIT.

package biomes

import graft "github.com/lrnxzz/graft"

const (
	Badlands               graft.BiomeID = 0
	BambooJungle           graft.BiomeID = 1
	BasaltDeltas           graft.BiomeID = 2
	Beach                  graft.BiomeID = 3
	BirchForest            graft.BiomeID = 4
	CherryGrove            graft.BiomeID = 5
	ColdOcean              graft.BiomeID = 6
	CrimsonForest          graft.BiomeID = 7
	DarkForest             graft.BiomeID = 8
	DeepColdOcean          graft.BiomeID = 9
	DeepDark               graft.BiomeID = 10
	DeepFrozenOcean        graft.BiomeID = 11
	DeepLukewarmOcean      graft.BiomeID = 12
	DeepOcean              graft.BiomeID = 13
	Desert                 graft.BiomeID = 14
	DripstoneCaves         graft.BiomeID = 15
	EndBarrens             graft.BiomeID = 16
	EndHighlands           graft.BiomeID = 17
	EndMidlands            graft.BiomeID = 18
	ErodedBadlands         graft.BiomeID = 19
	FlowerForest           graft.BiomeID = 20
	Forest                 graft.BiomeID = 21
	FrozenOcean            graft.BiomeID = 22
	FrozenPeaks            graft.BiomeID = 23
	FrozenRiver            graft.BiomeID = 24
	Grove                  graft.BiomeID = 25
	IceSpikes              graft.BiomeID = 26
	JaggedPeaks            graft.BiomeID = 27
	Jungle                 graft.BiomeID = 28
	LukewarmOcean          graft.BiomeID = 29
	LushCaves              graft.BiomeID = 30
	MangroveSwamp          graft.BiomeID = 31
	Meadow                 graft.BiomeID = 32
	MushroomFields         graft.BiomeID = 33
	NetherWastes           graft.BiomeID = 34
	Ocean                  graft.BiomeID = 35
	OldGrowthBirchForest   graft.BiomeID = 36
	OldGrowthPineTaiga     graft.BiomeID = 37
	OldGrowthSpruceTaiga   graft.BiomeID = 38
	Plains                 graft.BiomeID = 39
	River                  graft.BiomeID = 40
	Savanna                graft.BiomeID = 41
	SavannaPlateau         graft.BiomeID = 42
	SmallEndIslands        graft.BiomeID = 43
	SnowyBeach             graft.BiomeID = 44
	SnowyPlains            graft.BiomeID = 45
	SnowySlopes            graft.BiomeID = 46
	SnowyTaiga             graft.BiomeID = 47
	SoulSandValley         graft.BiomeID = 48
	SparseJungle           graft.BiomeID = 49
	StonyPeaks             graft.BiomeID = 50
	StonyShore             graft.BiomeID = 51
	SunflowerPlains        graft.BiomeID = 52
	Swamp                  graft.BiomeID = 53
	Taiga                  graft.BiomeID = 54
	TheEnd                 graft.BiomeID = 55
	TheVoid                graft.BiomeID = 56
	WarmOcean              graft.BiomeID = 57
	WarpedForest           graft.BiomeID = 58
	WindsweptForest        graft.BiomeID = 59
	WindsweptGravellyHills graft.BiomeID = 60
	WindsweptHills         graft.BiomeID = 61
	WindsweptSavanna       graft.BiomeID = 62
	WoodedBadlands         graft.BiomeID = 63
)
